title: AudioCC Lab
author:
  name: Joe Bloggs
  email: 'joe@example.com'
metadata:
    description: 'Grav is an easy to use, yet powerful, open source flat-file CMS'

member_tags: ["faculty", "post_doc", "phd", "master", "visitor", "undergraduate"]
